[project]
name = "backend"
version = "0.1.0"
description = "The repository for my backend practice"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg[binary,pool]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "rich>=15.0.0",
    "scalar-fastapi>=1.8.2",
    "sqlalchemy>=2.0.52",
    "sqlmodel>=0.0.39",
]
